server:
  port: 5555
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime:
    access: 900
    refresh: 2592000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
            allowedHeaders:
              - content-type
      routes:
        - id: auth-service
          uri: http://localhost:8088/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-app-auth
            - JwtAuthFilter
management:
  endpoints:
    web:
      exposure:
        include: "*"
